GET http://localhost:5028/games


###
GET http://localhost:5028/games/1683f699-5ec6-4535-bea9-22afd97dc67f

###
POST http://localhost:5028/games
Content-Type: application/json

{
  "genre": "Family",
  "price": 9.99,
  "releaseDate": "2024-07-01"
}

###
PUT http://localhost:5028/games/624408fe-0612-41a5-b6ad-cf3a0349d376
Content-Type: application/json

{
  "name": "Updated Game Name",
  "genre": "Family",
  "price": 9.99,
  "releaseDate": "2024-07-01"
}

###
DELETE http://localhost:5028/games/624408fe-0612-41a5-b6ad-cf3a0349d376

###
GET http://localhost:5028/genres