GET http://localhost:5028/games?pageNumber=1&pageSize=5


###
GET http://localhost:5028/games/1683f699-5ec6-4535-bea9-22afd97dc67f

###
POST http://localhost:5028/games
Content-Type: application/json

{
  "genreId": "1868DBA6-0869-4B0F-8544-CB6BC44DF606",
  "price": 9.99,
  "releaseDate": "2024-07-01",
  "name": "Test Game",
  "description": "This is a test game description."
}

###
PUT http://localhost:5028/games/624408fe-0612-41a5-b6ad-cf3a0349d376
Content-Type: application/json

{
  "name": "Updated Game Name",
  "genre": "Family",
  "price": 9.99,
  "releaseDate": "2024-07-01"
}

###
DELETE http://localhost:5028/games/865e94b8-3c98-4788-acf4-d3664abc95dd

###
GET http://localhost:5028/genres